### ISSUE TITLE
sqlite3.OperationalError: unknown tokenizer: collating

### ISSUE THREAD

**Issue by kazuiii** [l3uddz/plex_trash_fixer#1]
hello,
when I use the script, it detects the files to be deleted but, in spite of the emptying of the recycle garbage can and the optimization of the library, it does not delete anything.

Here is an extract of what is displayed at the end: 
`Setting 'deleted_at' from table 'metadata_items' to NULL for id: 2016
Traceback (most recent call last):
  File "/opt/plex_trash_fixer/plex_trash_fixer.py", line 161, in <module>
    set_field_null(database, 'metadata_items', 'deleted_at', deleted_item.id)
  File "/opt/plex_trash_fixer/plex_trash_fixer.py", line 131, in set_field_null
    cursor.execute(''' UPDATE {} SET {} = ? WHERE id = ? '''.format(table, field), (None, id))
sqlite3.OperationalError: unknown tokenizer: collating`

**Comment by wilpig** [comment]
https://forums.plex.tv/t/sqlite-error-1-unknown-tokenizer-collating/711224/4
